### ISSUE TITLE
Customize heyoffline texts

### ISSUE THREAD

**Issue by jaspoor** [oskarkrawczyk/heyoffline#18]
I am trying to change the texts of the heyoffline script. Unfortunately, i'm not being able to change it's options, like such:

new Heyoffline({
  text: {
    title: "Heading",
    content: "WarningMessage",
    button: "Close Alert"
  }
});

It tells me that "object is not a function". My console is telling me that "Heyoffline" is an object, not a function.
Without any adjustments, if I disconnect my wifi, it displays your heyoffline popup just fine.

Any clue what I am missing here?

TIA, Jasper

**Comment by nonameolsson** [comment]
How did you solve this?
