### ISSUE TITLE
Issues in Firefox 29.0.1

### ISSUE THREAD

**Issue by umeshabhat** [oskarkrawczyk/Heyoffline#25]
The script doesn't work on Mozilla Firefox 29.0.1 (Windows 7).

But works fine on the same machine with -
Google Chrome 35.0.1916.153 m
Opera 22.0.1471.70
Internet Explorer 11.0.9600

**Comment by sukima** [comment]
I can confirm this does not work in Firefox 37.0a2 (2015-02-23) (Developer Edition).
